# For full config options, check the docs:
#    docs.serverless.com

service: ig-njs

# You can pin your service to only deploy with a specific Serverless version
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
#  stage: dev
  region: ap-southeast-1
  memorySize: 128

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  exclude:
    - nbproject/**
#    - exclude-me.js
#    - exclude-me-dir/**
#  include:
#    - include-me.js
#    - include-me-dir/**

#plugins:
#  - serverless-plugins

functions:
  stats:
    handler: handler.stats
    timeout: 20 # Timeout in seconds, the default is 6 seconds
#    reservedConcurrency: 44 # Maximum concurrency (parallel executions), the default is 1000
    events:
      - http:
          path: stats
          method: get

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)

#    Define function environment variables here
#    environment:
#      variable2: value2