# For full config options, check the docs:
#    docs.serverless.com

service: ig-njs # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
#  stage: dev
  region: ap-southeast-1
  memorySize: 128

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  exclude:
    - nbproject/**
#    - exclude-me.js
#    - exclude-me-dir/**
#  include:
#    - include-me.js
#    - include-me-dir/**

#plugins:
#  - serverless-plugins

functions:
  hello:
    handler: handler.hello
#    events:
#      - http: ANY /
#      - http: 'ANY {proxy+}'
#    timeout: 11 # Timeout in seconds, the default is 6 seconds
#    reservedConcurrency: 44 # Maximum concurrency (parallel executions), the default is 1000

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
